<?php


/**
 * Base class that represents a query for the 'credit_card' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Sat Aug 25 00:34:26 2012
 *
 * @method     CreditCardQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     CreditCardQuery orderByAlias($order = Criteria::ASC) Order by the alias column
 * @method     CreditCardQuery orderByBrand($order = Criteria::ASC) Order by the brand column
 * @method     CreditCardQuery orderByNumber($order = Criteria::ASC) Order by the number column
 * @method     CreditCardQuery orderByExpiresAt($order = Criteria::ASC) Order by the expires_at column
 * @method     CreditCardQuery orderByOwner($order = Criteria::ASC) Order by the owner column
 * @method     CreditCardQuery orderByIsSelected($order = Criteria::ASC) Order by the is_selected column
 * @method     CreditCardQuery orderByUserId($order = Criteria::ASC) Order by the user_id column
 *
 * @method     CreditCardQuery groupById() Group by the id column
 * @method     CreditCardQuery groupByAlias() Group by the alias column
 * @method     CreditCardQuery groupByBrand() Group by the brand column
 * @method     CreditCardQuery groupByNumber() Group by the number column
 * @method     CreditCardQuery groupByExpiresAt() Group by the expires_at column
 * @method     CreditCardQuery groupByOwner() Group by the owner column
 * @method     CreditCardQuery groupByIsSelected() Group by the is_selected column
 * @method     CreditCardQuery groupByUserId() Group by the user_id column
 *
 * @method     CreditCardQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     CreditCardQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     CreditCardQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     CreditCardQuery leftJoinUser($relationAlias = null) Adds a LEFT JOIN clause to the query using the User relation
 * @method     CreditCardQuery rightJoinUser($relationAlias = null) Adds a RIGHT JOIN clause to the query using the User relation
 * @method     CreditCardQuery innerJoinUser($relationAlias = null) Adds a INNER JOIN clause to the query using the User relation
 *
 * @method     CreditCard findOne(PropelPDO $con = null) Return the first CreditCard matching the query
 * @method     CreditCard findOneOrCreate(PropelPDO $con = null) Return the first CreditCard matching the query, or a new CreditCard object populated from the query conditions when no match is found
 *
 * @method     CreditCard findOneById(int $id) Return the first CreditCard filtered by the id column
 * @method     CreditCard findOneByAlias(string $alias) Return the first CreditCard filtered by the alias column
 * @method     CreditCard findOneByBrand(string $brand) Return the first CreditCard filtered by the brand column
 * @method     CreditCard findOneByNumber(string $number) Return the first CreditCard filtered by the number column
 * @method     CreditCard findOneByExpiresAt(string $expires_at) Return the first CreditCard filtered by the expires_at column
 * @method     CreditCard findOneByOwner(string $owner) Return the first CreditCard filtered by the owner column
 * @method     CreditCard findOneByIsSelected(boolean $is_selected) Return the first CreditCard filtered by the is_selected column
 * @method     CreditCard findOneByUserId(int $user_id) Return the first CreditCard filtered by the user_id column
 *
 * @method     array findById(int $id) Return CreditCard objects filtered by the id column
 * @method     array findByAlias(string $alias) Return CreditCard objects filtered by the alias column
 * @method     array findByBrand(string $brand) Return CreditCard objects filtered by the brand column
 * @method     array findByNumber(string $number) Return CreditCard objects filtered by the number column
 * @method     array findByExpiresAt(string $expires_at) Return CreditCard objects filtered by the expires_at column
 * @method     array findByOwner(string $owner) Return CreditCard objects filtered by the owner column
 * @method     array findByIsSelected(boolean $is_selected) Return CreditCard objects filtered by the is_selected column
 * @method     array findByUserId(int $user_id) Return CreditCard objects filtered by the user_id column
 *
 * @package    propel.generator.lib.model.payment.om
 */
abstract class BaseCreditCardQuery extends ModelCriteria
{
    
    /**
     * Initializes internal state of BaseCreditCardQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'CreditCard', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new CreditCardQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     CreditCardQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return CreditCardQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof CreditCardQuery) {
            return $criteria;
        }
        $query = new CreditCardQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   CreditCard|CreditCard[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = CreditCardPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(CreditCardPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   CreditCard A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `ALIAS`, `BRAND`, `NUMBER`, `EXPIRES_AT`, `OWNER`, `IS_SELECTED`, `USER_ID` FROM `credit_card` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new CreditCard();
            $obj->hydrate($row);
            CreditCardPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return CreditCard|CreditCard[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|CreditCard[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(CreditCardPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(CreditCardPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(CreditCardPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the alias column
     *
     * Example usage:
     * <code>
     * $query->filterByAlias('fooValue');   // WHERE alias = 'fooValue'
     * $query->filterByAlias('%fooValue%'); // WHERE alias LIKE '%fooValue%'
     * </code>
     *
     * @param     string $alias The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByAlias($alias = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($alias)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $alias)) {
                $alias = str_replace('*', '%', $alias);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CreditCardPeer::ALIAS, $alias, $comparison);
    }

    /**
     * Filter the query on the brand column
     *
     * Example usage:
     * <code>
     * $query->filterByBrand('fooValue');   // WHERE brand = 'fooValue'
     * $query->filterByBrand('%fooValue%'); // WHERE brand LIKE '%fooValue%'
     * </code>
     *
     * @param     string $brand The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByBrand($brand = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($brand)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $brand)) {
                $brand = str_replace('*', '%', $brand);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CreditCardPeer::BRAND, $brand, $comparison);
    }

    /**
     * Filter the query on the number column
     *
     * Example usage:
     * <code>
     * $query->filterByNumber('fooValue');   // WHERE number = 'fooValue'
     * $query->filterByNumber('%fooValue%'); // WHERE number LIKE '%fooValue%'
     * </code>
     *
     * @param     string $number The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByNumber($number = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($number)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $number)) {
                $number = str_replace('*', '%', $number);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CreditCardPeer::NUMBER, $number, $comparison);
    }

    /**
     * Filter the query on the expires_at column
     *
     * Example usage:
     * <code>
     * $query->filterByExpiresAt('fooValue');   // WHERE expires_at = 'fooValue'
     * $query->filterByExpiresAt('%fooValue%'); // WHERE expires_at LIKE '%fooValue%'
     * </code>
     *
     * @param     string $expiresAt The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByExpiresAt($expiresAt = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($expiresAt)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $expiresAt)) {
                $expiresAt = str_replace('*', '%', $expiresAt);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CreditCardPeer::EXPIRES_AT, $expiresAt, $comparison);
    }

    /**
     * Filter the query on the owner column
     *
     * Example usage:
     * <code>
     * $query->filterByOwner('fooValue');   // WHERE owner = 'fooValue'
     * $query->filterByOwner('%fooValue%'); // WHERE owner LIKE '%fooValue%'
     * </code>
     *
     * @param     string $owner The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByOwner($owner = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($owner)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $owner)) {
                $owner = str_replace('*', '%', $owner);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(CreditCardPeer::OWNER, $owner, $comparison);
    }

    /**
     * Filter the query on the is_selected column
     *
     * Example usage:
     * <code>
     * $query->filterByIsSelected(true); // WHERE is_selected = true
     * $query->filterByIsSelected('yes'); // WHERE is_selected = true
     * </code>
     *
     * @param     boolean|string $isSelected The value to use as filter.
     *              Non-boolean arguments are converted using the following rules:
     *                * 1, '1', 'true',  'on',  and 'yes' are converted to boolean true
     *                * 0, '0', 'false', 'off', and 'no'  are converted to boolean false
     *              Check on string values is case insensitive (so 'FaLsE' is seen as 'false').
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByIsSelected($isSelected = null, $comparison = null)
    {
        if (is_string($isSelected)) {
            $is_selected = in_array(strtolower($isSelected), array('false', 'off', '-', 'no', 'n', '0', '')) ? false : true;
        }

        return $this->addUsingAlias(CreditCardPeer::IS_SELECTED, $isSelected, $comparison);
    }

    /**
     * Filter the query on the user_id column
     *
     * Example usage:
     * <code>
     * $query->filterByUserId(1234); // WHERE user_id = 1234
     * $query->filterByUserId(array(12, 34)); // WHERE user_id IN (12, 34)
     * $query->filterByUserId(array('min' => 12)); // WHERE user_id > 12
     * </code>
     *
     * @see       filterByUser()
     *
     * @param     mixed $userId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function filterByUserId($userId = null, $comparison = null)
    {
        if (is_array($userId)) {
            $useMinMax = false;
            if (isset($userId['min'])) {
                $this->addUsingAlias(CreditCardPeer::USER_ID, $userId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($userId['max'])) {
                $this->addUsingAlias(CreditCardPeer::USER_ID, $userId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(CreditCardPeer::USER_ID, $userId, $comparison);
    }

    /**
     * Filter the query by a related User object
     *
     * @param   User|PropelObjectCollection $user The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   CreditCardQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterByUser($user, $comparison = null)
    {
        if ($user instanceof User) {
            return $this
                ->addUsingAlias(CreditCardPeer::USER_ID, $user->getId(), $comparison);
        } elseif ($user instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(CreditCardPeer::USER_ID, $user->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterByUser() only accepts arguments of type User or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the User relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function joinUser($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('User');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'User');
        }

        return $this;
    }

    /**
     * Use the User relation User object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   UserQuery A secondary query class using the current class as primary query
     */
    public function useUserQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinUser($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'User', 'UserQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   CreditCard $creditCard Object to remove from the list of results
     *
     * @return CreditCardQuery The current query, for fluid interface
     */
    public function prune($creditCard = null)
    {
        if ($creditCard) {
            $this->addUsingAlias(CreditCardPeer::ID, $creditCard->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

} // BaseCreditCardQuery