<?php


/**
 * Base class that represents a query for the 'template' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Sat Aug 25 00:34:26 2012
 *
 * @method     TemplateQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     TemplateQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method     TemplateQuery orderByContent($order = Criteria::ASC) Order by the content column
 * @method     TemplateQuery orderBySubject($order = Criteria::ASC) Order by the subject column
 * @method     TemplateQuery orderBySellerPspConfigurationId($order = Criteria::ASC) Order by the seller_psp_configuration_id column
 * @method     TemplateQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     TemplateQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 *
 * @method     TemplateQuery groupById() Group by the id column
 * @method     TemplateQuery groupByName() Group by the name column
 * @method     TemplateQuery groupByContent() Group by the content column
 * @method     TemplateQuery groupBySubject() Group by the subject column
 * @method     TemplateQuery groupBySellerPspConfigurationId() Group by the seller_psp_configuration_id column
 * @method     TemplateQuery groupByCreatedAt() Group by the created_at column
 * @method     TemplateQuery groupByUpdatedAt() Group by the updated_at column
 *
 * @method     TemplateQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     TemplateQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     TemplateQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     TemplateQuery leftJoinSellerPspConfiguration($relationAlias = null) Adds a LEFT JOIN clause to the query using the SellerPspConfiguration relation
 * @method     TemplateQuery rightJoinSellerPspConfiguration($relationAlias = null) Adds a RIGHT JOIN clause to the query using the SellerPspConfiguration relation
 * @method     TemplateQuery innerJoinSellerPspConfiguration($relationAlias = null) Adds a INNER JOIN clause to the query using the SellerPspConfiguration relation
 *
 * @method     Template findOne(PropelPDO $con = null) Return the first Template matching the query
 * @method     Template findOneOrCreate(PropelPDO $con = null) Return the first Template matching the query, or a new Template object populated from the query conditions when no match is found
 *
 * @method     Template findOneById(int $id) Return the first Template filtered by the id column
 * @method     Template findOneByName(string $name) Return the first Template filtered by the name column
 * @method     Template findOneByContent(string $content) Return the first Template filtered by the content column
 * @method     Template findOneBySubject(string $subject) Return the first Template filtered by the subject column
 * @method     Template findOneBySellerPspConfigurationId(int $seller_psp_configuration_id) Return the first Template filtered by the seller_psp_configuration_id column
 * @method     Template findOneByCreatedAt(string $created_at) Return the first Template filtered by the created_at column
 * @method     Template findOneByUpdatedAt(string $updated_at) Return the first Template filtered by the updated_at column
 *
 * @method     array findById(int $id) Return Template objects filtered by the id column
 * @method     array findByName(string $name) Return Template objects filtered by the name column
 * @method     array findByContent(string $content) Return Template objects filtered by the content column
 * @method     array findBySubject(string $subject) Return Template objects filtered by the subject column
 * @method     array findBySellerPspConfigurationId(int $seller_psp_configuration_id) Return Template objects filtered by the seller_psp_configuration_id column
 * @method     array findByCreatedAt(string $created_at) Return Template objects filtered by the created_at column
 * @method     array findByUpdatedAt(string $updated_at) Return Template objects filtered by the updated_at column
 *
 * @package    propel.generator.lib.model.payment.om
 */
abstract class BaseTemplateQuery extends ModelCriteria
{
    
    /**
     * Initializes internal state of BaseTemplateQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Template', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new TemplateQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     TemplateQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return TemplateQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof TemplateQuery) {
            return $criteria;
        }
        $query = new TemplateQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Template|Template[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = TemplatePeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(TemplatePeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Template A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `NAME`, `CONTENT`, `SUBJECT`, `SELLER_PSP_CONFIGURATION_ID`, `CREATED_AT`, `UPDATED_AT` FROM `template` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Template();
            $obj->hydrate($row);
            TemplatePeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Template|Template[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Template[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(TemplatePeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(TemplatePeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(TemplatePeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the name column
     *
     * Example usage:
     * <code>
     * $query->filterByName('fooValue');   // WHERE name = 'fooValue'
     * $query->filterByName('%fooValue%'); // WHERE name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $name The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterByName($name = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($name)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $name)) {
                $name = str_replace('*', '%', $name);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TemplatePeer::NAME, $name, $comparison);
    }

    /**
     * Filter the query on the content column
     *
     * Example usage:
     * <code>
     * $query->filterByContent('fooValue');   // WHERE content = 'fooValue'
     * $query->filterByContent('%fooValue%'); // WHERE content LIKE '%fooValue%'
     * </code>
     *
     * @param     string $content The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterByContent($content = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($content)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $content)) {
                $content = str_replace('*', '%', $content);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TemplatePeer::CONTENT, $content, $comparison);
    }

    /**
     * Filter the query on the subject column
     *
     * Example usage:
     * <code>
     * $query->filterBySubject('fooValue');   // WHERE subject = 'fooValue'
     * $query->filterBySubject('%fooValue%'); // WHERE subject LIKE '%fooValue%'
     * </code>
     *
     * @param     string $subject The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterBySubject($subject = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($subject)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $subject)) {
                $subject = str_replace('*', '%', $subject);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(TemplatePeer::SUBJECT, $subject, $comparison);
    }

    /**
     * Filter the query on the seller_psp_configuration_id column
     *
     * Example usage:
     * <code>
     * $query->filterBySellerPspConfigurationId(1234); // WHERE seller_psp_configuration_id = 1234
     * $query->filterBySellerPspConfigurationId(array(12, 34)); // WHERE seller_psp_configuration_id IN (12, 34)
     * $query->filterBySellerPspConfigurationId(array('min' => 12)); // WHERE seller_psp_configuration_id > 12
     * </code>
     *
     * @see       filterBySellerPspConfiguration()
     *
     * @param     mixed $sellerPspConfigurationId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterBySellerPspConfigurationId($sellerPspConfigurationId = null, $comparison = null)
    {
        if (is_array($sellerPspConfigurationId)) {
            $useMinMax = false;
            if (isset($sellerPspConfigurationId['min'])) {
                $this->addUsingAlias(TemplatePeer::SELLER_PSP_CONFIGURATION_ID, $sellerPspConfigurationId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($sellerPspConfigurationId['max'])) {
                $this->addUsingAlias(TemplatePeer::SELLER_PSP_CONFIGURATION_ID, $sellerPspConfigurationId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TemplatePeer::SELLER_PSP_CONFIGURATION_ID, $sellerPspConfigurationId, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(TemplatePeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(TemplatePeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TemplatePeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(TemplatePeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(TemplatePeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(TemplatePeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query by a related SellerPspConfiguration object
     *
     * @param   SellerPspConfiguration|PropelObjectCollection $sellerPspConfiguration The related object(s) to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   TemplateQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBySellerPspConfiguration($sellerPspConfiguration, $comparison = null)
    {
        if ($sellerPspConfiguration instanceof SellerPspConfiguration) {
            return $this
                ->addUsingAlias(TemplatePeer::SELLER_PSP_CONFIGURATION_ID, $sellerPspConfiguration->getId(), $comparison);
        } elseif ($sellerPspConfiguration instanceof PropelObjectCollection) {
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }

            return $this
                ->addUsingAlias(TemplatePeer::SELLER_PSP_CONFIGURATION_ID, $sellerPspConfiguration->toKeyValue('PrimaryKey', 'Id'), $comparison);
        } else {
            throw new PropelException('filterBySellerPspConfiguration() only accepts arguments of type SellerPspConfiguration or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the SellerPspConfiguration relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function joinSellerPspConfiguration($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('SellerPspConfiguration');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'SellerPspConfiguration');
        }

        return $this;
    }

    /**
     * Use the SellerPspConfiguration relation SellerPspConfiguration object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   SellerPspConfigurationQuery A secondary query class using the current class as primary query
     */
    public function useSellerPspConfigurationQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinSellerPspConfiguration($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'SellerPspConfiguration', 'SellerPspConfigurationQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Template $template Object to remove from the list of results
     *
     * @return TemplateQuery The current query, for fluid interface
     */
    public function prune($template = null)
    {
        if ($template) {
            $this->addUsingAlias(TemplatePeer::ID, $template->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

	// timestampable behavior
	
	/**
	 * Filter by the latest updated
	 *
	 * @param      int $nbDays Maximum age of the latest update in days
	 *
	 * @return     TemplateQuery The current query, for fluid interface
	 */
	public function recentlyUpdated($nbDays = 7)
	{
	    return $this->addUsingAlias(TemplatePeer::UPDATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
	}
	
	/**
	 * Order by update date desc
	 *
	 * @return     TemplateQuery The current query, for fluid interface
	 */
	public function lastUpdatedFirst()
	{
	    return $this->addDescendingOrderByColumn(TemplatePeer::UPDATED_AT);
	}
	
	/**
	 * Order by update date asc
	 *
	 * @return     TemplateQuery The current query, for fluid interface
	 */
	public function firstUpdatedFirst()
	{
	    return $this->addAscendingOrderByColumn(TemplatePeer::UPDATED_AT);
	}
	
	/**
	 * Filter by the latest created
	 *
	 * @param      int $nbDays Maximum age of in days
	 *
	 * @return     TemplateQuery The current query, for fluid interface
	 */
	public function recentlyCreated($nbDays = 7)
	{
	    return $this->addUsingAlias(TemplatePeer::CREATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
	}
	
	/**
	 * Order by create date desc
	 *
	 * @return     TemplateQuery The current query, for fluid interface
	 */
	public function lastCreatedFirst()
	{
	    return $this->addDescendingOrderByColumn(TemplatePeer::CREATED_AT);
	}
	
	/**
	 * Order by create date asc
	 *
	 * @return     TemplateQuery The current query, for fluid interface
	 */
	public function firstCreatedFirst()
	{
	    return $this->addAscendingOrderByColumn(TemplatePeer::CREATED_AT);
	}
} // BaseTemplateQuery