<?php


/**
 * Base class that represents a query for the 'seller' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Sat Aug 25 00:34:26 2012
 *
 * @method     SellerQuery orderById($order = Criteria::ASC) Order by the id column
 * @method     SellerQuery orderByName($order = Criteria::ASC) Order by the name column
 * @method     SellerQuery orderByDescription($order = Criteria::ASC) Order by the description column
 * @method     SellerQuery orderByIdent($order = Criteria::ASC) Order by the ident column
 * @method     SellerQuery orderByShaKey($order = Criteria::ASC) Order by the sha_key column
 * @method     SellerQuery orderByCreatedAt($order = Criteria::ASC) Order by the created_at column
 * @method     SellerQuery orderByUpdatedAt($order = Criteria::ASC) Order by the updated_at column
 * @method     SellerQuery orderBySluggedName($order = Criteria::ASC) Order by the slugged_name column
 *
 * @method     SellerQuery groupById() Group by the id column
 * @method     SellerQuery groupByName() Group by the name column
 * @method     SellerQuery groupByDescription() Group by the description column
 * @method     SellerQuery groupByIdent() Group by the ident column
 * @method     SellerQuery groupByShaKey() Group by the sha_key column
 * @method     SellerQuery groupByCreatedAt() Group by the created_at column
 * @method     SellerQuery groupByUpdatedAt() Group by the updated_at column
 * @method     SellerQuery groupBySluggedName() Group by the slugged_name column
 *
 * @method     SellerQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method     SellerQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method     SellerQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method     SellerQuery leftJoinSellerPspConfiguration($relationAlias = null) Adds a LEFT JOIN clause to the query using the SellerPspConfiguration relation
 * @method     SellerQuery rightJoinSellerPspConfiguration($relationAlias = null) Adds a RIGHT JOIN clause to the query using the SellerPspConfiguration relation
 * @method     SellerQuery innerJoinSellerPspConfiguration($relationAlias = null) Adds a INNER JOIN clause to the query using the SellerPspConfiguration relation
 *
 * @method     Seller findOne(PropelPDO $con = null) Return the first Seller matching the query
 * @method     Seller findOneOrCreate(PropelPDO $con = null) Return the first Seller matching the query, or a new Seller object populated from the query conditions when no match is found
 *
 * @method     Seller findOneById(int $id) Return the first Seller filtered by the id column
 * @method     Seller findOneByName(string $name) Return the first Seller filtered by the name column
 * @method     Seller findOneByDescription(string $description) Return the first Seller filtered by the description column
 * @method     Seller findOneByIdent(string $ident) Return the first Seller filtered by the ident column
 * @method     Seller findOneByShaKey(string $sha_key) Return the first Seller filtered by the sha_key column
 * @method     Seller findOneByCreatedAt(string $created_at) Return the first Seller filtered by the created_at column
 * @method     Seller findOneByUpdatedAt(string $updated_at) Return the first Seller filtered by the updated_at column
 * @method     Seller findOneBySluggedName(string $slugged_name) Return the first Seller filtered by the slugged_name column
 *
 * @method     array findById(int $id) Return Seller objects filtered by the id column
 * @method     array findByName(string $name) Return Seller objects filtered by the name column
 * @method     array findByDescription(string $description) Return Seller objects filtered by the description column
 * @method     array findByIdent(string $ident) Return Seller objects filtered by the ident column
 * @method     array findByShaKey(string $sha_key) Return Seller objects filtered by the sha_key column
 * @method     array findByCreatedAt(string $created_at) Return Seller objects filtered by the created_at column
 * @method     array findByUpdatedAt(string $updated_at) Return Seller objects filtered by the updated_at column
 * @method     array findBySluggedName(string $slugged_name) Return Seller objects filtered by the slugged_name column
 *
 * @package    propel.generator.lib.model.payment.om
 */
abstract class BaseSellerQuery extends ModelCriteria
{
    
    /**
     * Initializes internal state of BaseSellerQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Seller', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new SellerQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     SellerQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return SellerQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof SellerQuery) {
            return $criteria;
        }
        $query = new SellerQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query 
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Seller|Seller[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = SellerPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(SellerPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Seller A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `NAME`, `DESCRIPTION`, `IDENT`, `SHA_KEY`, `CREATED_AT`, `UPDATED_AT`, `SLUGGED_NAME` FROM `seller` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
			$stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Seller();
            $obj->hydrate($row);
            SellerPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Seller|Seller[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Seller[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(SellerPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(SellerPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(SellerPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the name column
     *
     * Example usage:
     * <code>
     * $query->filterByName('fooValue');   // WHERE name = 'fooValue'
     * $query->filterByName('%fooValue%'); // WHERE name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $name The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByName($name = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($name)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $name)) {
                $name = str_replace('*', '%', $name);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SellerPeer::NAME, $name, $comparison);
    }

    /**
     * Filter the query on the description column
     *
     * Example usage:
     * <code>
     * $query->filterByDescription('fooValue');   // WHERE description = 'fooValue'
     * $query->filterByDescription('%fooValue%'); // WHERE description LIKE '%fooValue%'
     * </code>
     *
     * @param     string $description The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByDescription($description = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($description)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $description)) {
                $description = str_replace('*', '%', $description);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SellerPeer::DESCRIPTION, $description, $comparison);
    }

    /**
     * Filter the query on the ident column
     *
     * Example usage:
     * <code>
     * $query->filterByIdent('fooValue');   // WHERE ident = 'fooValue'
     * $query->filterByIdent('%fooValue%'); // WHERE ident LIKE '%fooValue%'
     * </code>
     *
     * @param     string $ident The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByIdent($ident = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($ident)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $ident)) {
                $ident = str_replace('*', '%', $ident);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SellerPeer::IDENT, $ident, $comparison);
    }

    /**
     * Filter the query on the sha_key column
     *
     * Example usage:
     * <code>
     * $query->filterByShaKey('fooValue');   // WHERE sha_key = 'fooValue'
     * $query->filterByShaKey('%fooValue%'); // WHERE sha_key LIKE '%fooValue%'
     * </code>
     *
     * @param     string $shaKey The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByShaKey($shaKey = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($shaKey)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $shaKey)) {
                $shaKey = str_replace('*', '%', $shaKey);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SellerPeer::SHA_KEY, $shaKey, $comparison);
    }

    /**
     * Filter the query on the created_at column
     *
     * Example usage:
     * <code>
     * $query->filterByCreatedAt('2011-03-14'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt('now'); // WHERE created_at = '2011-03-14'
     * $query->filterByCreatedAt(array('max' => 'yesterday')); // WHERE created_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $createdAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByCreatedAt($createdAt = null, $comparison = null)
    {
        if (is_array($createdAt)) {
            $useMinMax = false;
            if (isset($createdAt['min'])) {
                $this->addUsingAlias(SellerPeer::CREATED_AT, $createdAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($createdAt['max'])) {
                $this->addUsingAlias(SellerPeer::CREATED_AT, $createdAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(SellerPeer::CREATED_AT, $createdAt, $comparison);
    }

    /**
     * Filter the query on the updated_at column
     *
     * Example usage:
     * <code>
     * $query->filterByUpdatedAt('2011-03-14'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt('now'); // WHERE updated_at = '2011-03-14'
     * $query->filterByUpdatedAt(array('max' => 'yesterday')); // WHERE updated_at > '2011-03-13'
     * </code>
     *
     * @param     mixed $updatedAt The value to use as filter.
     *              Values can be integers (unix timestamps), DateTime objects, or strings.
     *              Empty strings are treated as NULL.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterByUpdatedAt($updatedAt = null, $comparison = null)
    {
        if (is_array($updatedAt)) {
            $useMinMax = false;
            if (isset($updatedAt['min'])) {
                $this->addUsingAlias(SellerPeer::UPDATED_AT, $updatedAt['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($updatedAt['max'])) {
                $this->addUsingAlias(SellerPeer::UPDATED_AT, $updatedAt['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(SellerPeer::UPDATED_AT, $updatedAt, $comparison);
    }

    /**
     * Filter the query on the slugged_name column
     *
     * Example usage:
     * <code>
     * $query->filterBySluggedName('fooValue');   // WHERE slugged_name = 'fooValue'
     * $query->filterBySluggedName('%fooValue%'); // WHERE slugged_name LIKE '%fooValue%'
     * </code>
     *
     * @param     string $sluggedName The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function filterBySluggedName($sluggedName = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($sluggedName)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $sluggedName)) {
                $sluggedName = str_replace('*', '%', $sluggedName);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SellerPeer::SLUGGED_NAME, $sluggedName, $comparison);
    }

    /**
     * Filter the query by a related SellerPspConfiguration object
     *
     * @param   SellerPspConfiguration|PropelObjectCollection $sellerPspConfiguration  the related object to use as filter
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return   SellerQuery The current query, for fluid interface
     * @throws   PropelException - if the provided filter is invalid.
     */
    public function filterBySellerPspConfiguration($sellerPspConfiguration, $comparison = null)
    {
        if ($sellerPspConfiguration instanceof SellerPspConfiguration) {
            return $this
                ->addUsingAlias(SellerPeer::ID, $sellerPspConfiguration->getSellerId(), $comparison);
        } elseif ($sellerPspConfiguration instanceof PropelObjectCollection) {
            return $this
                ->useSellerPspConfigurationQuery()
                ->filterByPrimaryKeys($sellerPspConfiguration->getPrimaryKeys())
                ->endUse();
        } else {
            throw new PropelException('filterBySellerPspConfiguration() only accepts arguments of type SellerPspConfiguration or PropelCollection');
        }
    }

    /**
     * Adds a JOIN clause to the query using the SellerPspConfiguration relation
     *
     * @param     string $relationAlias optional alias for the relation
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function joinSellerPspConfiguration($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        $tableMap = $this->getTableMap();
        $relationMap = $tableMap->getRelation('SellerPspConfiguration');

        // create a ModelJoin object for this join
        $join = new ModelJoin();
        $join->setJoinType($joinType);
        $join->setRelationMap($relationMap, $this->useAliasInSQL ? $this->getModelAlias() : null, $relationAlias);
        if ($previousJoin = $this->getPreviousJoin()) {
            $join->setPreviousJoin($previousJoin);
        }

        // add the ModelJoin to the current object
        if ($relationAlias) {
            $this->addAlias($relationAlias, $relationMap->getRightTable()->getName());
            $this->addJoinObject($join, $relationAlias);
        } else {
            $this->addJoinObject($join, 'SellerPspConfiguration');
        }

        return $this;
    }

    /**
     * Use the SellerPspConfiguration relation SellerPspConfiguration object
     *
     * @see       useQuery()
     *
     * @param     string $relationAlias optional alias for the relation,
     *                                   to be used as main alias in the secondary query
     * @param     string $joinType Accepted values are null, 'left join', 'right join', 'inner join'
     *
     * @return   SellerPspConfigurationQuery A secondary query class using the current class as primary query
     */
    public function useSellerPspConfigurationQuery($relationAlias = null, $joinType = Criteria::INNER_JOIN)
    {
        return $this
            ->joinSellerPspConfiguration($relationAlias, $joinType)
            ->useQuery($relationAlias ? $relationAlias : 'SellerPspConfiguration', 'SellerPspConfigurationQuery');
    }

    /**
     * Exclude object from result
     *
     * @param   Seller $seller Object to remove from the list of results
     *
     * @return SellerQuery The current query, for fluid interface
     */
    public function prune($seller = null)
    {
        if ($seller) {
            $this->addUsingAlias(SellerPeer::ID, $seller->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

	// timestampable behavior
	
	/**
	 * Filter by the latest updated
	 *
	 * @param      int $nbDays Maximum age of the latest update in days
	 *
	 * @return     SellerQuery The current query, for fluid interface
	 */
	public function recentlyUpdated($nbDays = 7)
	{
	    return $this->addUsingAlias(SellerPeer::UPDATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
	}
	
	/**
	 * Order by update date desc
	 *
	 * @return     SellerQuery The current query, for fluid interface
	 */
	public function lastUpdatedFirst()
	{
	    return $this->addDescendingOrderByColumn(SellerPeer::UPDATED_AT);
	}
	
	/**
	 * Order by update date asc
	 *
	 * @return     SellerQuery The current query, for fluid interface
	 */
	public function firstUpdatedFirst()
	{
	    return $this->addAscendingOrderByColumn(SellerPeer::UPDATED_AT);
	}
	
	/**
	 * Filter by the latest created
	 *
	 * @param      int $nbDays Maximum age of in days
	 *
	 * @return     SellerQuery The current query, for fluid interface
	 */
	public function recentlyCreated($nbDays = 7)
	{
	    return $this->addUsingAlias(SellerPeer::CREATED_AT, time() - $nbDays * 24 * 60 * 60, Criteria::GREATER_EQUAL);
	}
	
	/**
	 * Order by create date desc
	 *
	 * @return     SellerQuery The current query, for fluid interface
	 */
	public function lastCreatedFirst()
	{
	    return $this->addDescendingOrderByColumn(SellerPeer::CREATED_AT);
	}
	
	/**
	 * Order by create date asc
	 *
	 * @return     SellerQuery The current query, for fluid interface
	 */
	public function firstCreatedFirst()
	{
	    return $this->addAscendingOrderByColumn(SellerPeer::CREATED_AT);
	}
	// sluggable behavior
	
	/**
	 * Filter the query on the slug column
	 *
	 * @param     string $slug The value to use as filter.
	 *
	 * @return    SellerQuery The current query, for fluid interface
	 */
	public function filterBySlug($slug)
	{
	    return $this->addUsingAlias(SellerPeer::SLUGGED_NAME, $slug, Criteria::EQUAL);
	}
	
	/**
	 * Find one object based on its slug
	 *
	 * @param     string $slug The value to use as filter.
	 * @param     PropelPDO $con The optional connection object
	 *
	 * @return    Seller the result, formatted by the current formatter
	 */
	public function findOneBySlug($slug, $con = null)
	{
	    return $this->filterBySlug($slug)->findOne($con);
	}

} // BaseSellerQuery