<?php



/**
 * This class defines the structure of the 'order' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Sat Aug 25 00:34:26 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.payment.map
 */
class OrderTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.payment.map.OrderTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('order');
        $this->setPhpName('Order');
        $this->setClassname('Order');
        $this->setPackage('lib.model.payment');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('REFERENCE', 'Reference', 'VARCHAR', false, 45, null);
        $this->addColumn('AMOUNT', 'Amount', 'DECIMAL', false, null, null);
        $this->addColumn('HASH', 'Hash', 'VARCHAR', true, 255, null);
        $this->addColumn('USER_ID', 'UserId', 'INTEGER', false, null, null);
        $this->addForeignKey('SELLER_PSP_CONFIGURATION_ID', 'SellerPspConfigurationId', 'INTEGER', 'seller_psp_configuration', 'ID', true, null, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('SellerPspConfiguration', 'SellerPspConfiguration', RelationMap::MANY_TO_ONE, array('seller_psp_configuration_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('Transaction', 'Transaction', RelationMap::ONE_TO_MANY, array('id' => 'order_id', ), 'CASCADE', null, 'Transactions');
        $this->addRelation('OrderExtraProperty', 'OrderExtraProperty', RelationMap::ONE_TO_MANY, array('id' => 'order_id', ), 'CASCADE', null, 'OrderExtraPropertys');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', 'disable_updated_at' => 'false', ),
            'extra_properties' => array('properties_table' => '', 'property_name_column' => 'property_name', 'property_value_column' => 'property_value', 'default_properties' => '', 'normalize' => 'true', 'throw_error' => 'true', ),
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
        );
    } // getBehaviors()

} // OrderTableMap
