<?php



/**
 * This class defines the structure of the 'seller_psp_configuration' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Sat Aug 25 00:34:26 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.payment.map
 */
class SellerPspConfigurationTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.payment.map.SellerPspConfigurationTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('seller_psp_configuration');
        $this->setPhpName('SellerPspConfiguration');
        $this->setClassname('SellerPspConfiguration');
        $this->setPackage('lib.model.payment');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addForeignKey('SELLER_ID', 'SellerId', 'INTEGER', 'seller', 'ID', true, null, null);
        $this->addColumn('PSP_NAME', 'PspName', 'VARCHAR', true, 255, null);
        $this->addColumn('SERVICE_TYPE', 'ServiceType', 'VARCHAR', true, 45, 'pme');
        $this->addColumn('PSP_CONFIGURATION', 'PspConfiguration', 'OBJECT', true, null, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Seller', 'Seller', RelationMap::MANY_TO_ONE, array('seller_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('Order', 'Order', RelationMap::ONE_TO_MANY, array('id' => 'seller_psp_configuration_id', ), 'CASCADE', null, 'Orders');
        $this->addRelation('Template', 'Template', RelationMap::ONE_TO_MANY, array('id' => 'seller_psp_configuration_id', ), 'CASCADE', null, 'Templates');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', 'disable_updated_at' => 'false', ),
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // SellerPspConfigurationTableMap
