<?php



/**
 * This class defines the structure of the 'transaction' table.
 *
 *
 * This class was autogenerated by Propel 1.6.6 on:
 *
 * Sat Aug 25 00:34:26 2012
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.payment.map
 */
class TransactionTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.payment.map.TransactionTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('transaction');
        $this->setPhpName('Transaction');
        $this->setClassname('Transaction');
        $this->setPackage('lib.model.payment');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
        $this->addColumn('REFERENCE', 'Reference', 'VARCHAR', true, 45, null);
        $this->addColumn('TAXES', 'Taxes', 'DECIMAL', false, null, null);
        $this->addColumn('CURRENCY', 'Currency', 'VARCHAR', true, 45, null);
        $this->addColumn('STATUS', 'Status', 'VARCHAR', true, 45, null);
        $this->addColumn('IS_PROCESSED', 'IsProcessed', 'BOOLEAN', true, 1, false);
        $this->addForeignKey('ORDER_ID', 'OrderId', 'INTEGER', 'order', 'ID', true, null, null);
        $this->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null, null);
        $this->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null, null);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
        $this->addRelation('Order', 'Order', RelationMap::MANY_TO_ONE, array('order_id' => 'id', ), 'CASCADE', null);
        $this->addRelation('TransactionExtraProperty', 'TransactionExtraProperty', RelationMap::ONE_TO_MANY, array('id' => 'transaction_id', ), 'CASCADE', null, 'TransactionExtraPropertys');
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', 'disable_updated_at' => 'false', ),
            'extra_properties' => array('properties_table' => '', 'property_name_column' => 'property_name', 'property_value_column' => 'property_value', 'default_properties' => '', 'normalize' => 'true', 'throw_error' => 'true', ),
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
            'symfony_timestampable' => array('create_column' => 'created_at', 'update_column' => 'updated_at', ),
        );
    } // getBehaviors()

} // TransactionTableMap
